// LOCALHOST
### Get all commands
GET http://localhost:8080/commands

### Create command
POST http://localhost:8080/commands HTTP/1.1
content-type: application/json

{
    "softwareType": "Test3",
    "operatingSys": "Test",
    "command": "Testcommand",
    "description": "Testdescription",
    "authorId": "TestauthorId",
    "otherShortCut": "TestotherShortCut"
}

### Update a command
PUT http://localhost:8080/commands/62827a38406c271622161351 HTTP/1.1
content-type: application/json

{
    "softwareType": "Test Type update",
    "operatingSys": "TestoperatingSys",
    "command": "Testcommand",
    "description": "Testdescription",
    "authorId": "TestauthorId",
    "otherShortCut": "TestotherShortCut"
}

### DELETE contact
DELETE http://localhost:8080/commands/628650c7b8a66ea2f459332c
// PR